feat(KINGU-50): primary UIkit button structure with stories
kinguru-io/kinguru-next pull request #345
Opened 2024-01-24 14:46 UTC by kiruushaaa

2024-01-24 15:54 UTC, edelwud requested changes

2024-01-24 15:54 UTC, edelwud commented on src/components/uikit/Button/Button.tsx
>        default: {
давай этот вариант переименуем в primary

2024-01-24 15:54 UTC, edelwud commented on src/components/uikit/Button/Button.tsx
> +      unfilled: {
а этот назовем outline

2024-01-24 15:54 UTC, edelwud commented on src/components/uikit/Button/Button.stories.ts
>    tags: ["autodocs"],
todo: подумать, чо писать в теги, чтобы потом было удобно пользоваться сторибуком

2024-01-24 15:54 UTC, edelwud commented on src/components/uikit/Button/Button.tsx
> +      {icon}
Надо протестить вариант с иконкой, добавить тоже его в сторибук
Кажется, лучше будет обернуть иконку в `styled.div`, будет проще с ней работать
```suggestion
      {icon && <styled.div display="inline-block">{icon}</styled.div>}
```

2024-01-24 15:58 UTC, edelwud commented on src/components/uikit/Button/Button.tsx
> +      {icon}
вообще, в идеале - отдельные свойства isLoading, isDisabled, но об этом лучше говорить с дизайнером, сами придумать, конечно, можем, главное чтобы она потом эти кнопки использовала

2024-01-24 16:08 UTC, kiruushaaa commented on src/components/uikit/Button/Button.tsx
> +      {icon}
насчет вида `isDisabled` да. это в целом состояние кнопки, которая зависит 100% от дизайна.

насчет загрузки не уверен. кнопка это кнопка, поэтому кажется лодер лучше рядом класть и делать его отдельным компонентом. тогда состояние кнопки будет регулироваться снаружи типа `disabled={isLoading}`

2024-01-24 16:11 UTC, kiruushaaa commented on src/components/uikit/Button/Button.stories.ts
>    tags: ["autodocs"],
много чего можно сделать https://storybook.js.org/docs/writing-docs/autodocs

2024-01-24 16:30 UTC, edelwud commented on src/components/uikit/Button/Button.tsx
> +      {icon}
согласен, давай сделаем компонент Spinner, в качестве референса можно попробовать взять вот это https://loading.io/css/

2024-01-24 18:03 UTC, edelwud reviewed
Все ок, давай ещё добавим спиннер и опцию для него

2024-01-25 07:30 UTC, edelwud approved these changes

2024-01-25 07:31 UTC, merged