feat: UI kit dropdown
kinguru-io/kinguru-next pull request #427
Opened 2024-02-10 17:28 UTC by okyxxxf

Создал компонент выдаюшее меню

2024-02-10 17:51 UTC, kiruushaaa requested changes

2024-02-10 17:51 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.recipe.ts
> +    },
просто поменять на аттрибут `data-hidden`, где `&[data-hidden=true]: { display: 'none' }`

или оставить `visibility`, но описать тип через юнион `'hidden' | 'visible'`

2024-02-10 17:51 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.recipe.ts
> +    },
кажется полоску внизу легче делать через `borderBlockEnd`, а обертке padding задать

2024-02-10 17:51 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.tsx
> +  children: React.ReactNode[];
просто React.ReactNode ? или оно так не принимает если children массив?

2024-02-10 17:51 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.tsx
> +export const Dropdown = ({
консистентность: `export function Dropdown` и добавить index с экспортами (глянь другие компоненты)

2024-02-10 17:51 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.recipe.ts
> +    boxShadow: "0 4px 4px 0 #00000040",
![image](https://github.com/kinguru-io/kinguru-next/assets/18754878/fce72a6c-27bc-4270-a1f0-71badebe6160)

2024-02-10 17:51 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.recipe.ts
> +    boxShadow: "0 4px 4px 0 #00000040",
копируй стили через ПКМ
`box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);`

2024-02-12 19:12 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.stories.tsx
>  } satisfies Meta<typeof Dropdown>;
для сторис можно добавить `args: { hidden: 'boolean' }`

2024-02-13 10:21 UTC, edelwud requested changes

2024-02-13 10:21 UTC, edelwud commented on src/components/uikit/Dropdown/Dropdown.tsx
> +}
а для чего он?

2024-02-13 10:21 UTC, edelwud commented on src/components/uikit/Dropdown/Dropdown.recipe.ts
> +    "&[data-hidden=true]": { display: "none" },
добавь в рецепт zIndex: "dropdown" (его в panda.config.ts унести нужно будет, в токены) и цвет фона, а то он у тебя прозрачный

2024-02-13 10:24 UTC, okyxxxf commented on src/components/uikit/Dropdown/Dropdown.tsx
> +}
наверное, чтобы было понятнее куда инициатора засунуть

2024-02-13 10:25 UTC, edelwud commented on panda.config.ts
> +import { dropdownRecipe } from "@/components/uikit/Dropdown/Dropdown.recipe";
тут надо заменить 
```suggestion
import { dropdownRecipe } from "./src/components/uikit/Dropdown/Dropdown.recipe";
```

2024-02-13 10:28 UTC, edelwud commented on src/components/uikit/Dropdown/Dropdown.tsx
> +}
было бы полезно, если бы ты трекал в этом копоненте клик на инициатора и раскрывал бы дропдаун, если клик бы был

2024-02-13 10:30 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.tsx
> +}
заметил тоже. появилось в голове использовать https://panda-css.com/docs/concepts/slot-recipes#usage-in-jsx

> почему именно через Object property?
- возможность использовать общий контекст для передачи нужных пропсов например той же менюшке. сейчас это не имеет значения, потому что нет задачи, но для расширяемости прям хорошо выглядит. то есть сейчас достаточно инкапсуляции через те же дата атрибуты с Child selector `.child1[data-...] + .child2 { <css> }` для компонента Dropdown.Initiator. из проблем наверное только хардкод кнопки с нужным лейблом или не нарушая вложенности тегов html добавить абсолют псевдо кнопки поверх нужного контента (как например я добавлял блюр и градиент)
- просто удобная инкапсуляция (получится то же самое что и для карточек из кита). подсмотрел в https://react-bootstrap.netlify.app/docs/components/dropdowns/

2024-02-13 10:32 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.tsx
> +}
Саше скидывал в личку демку. такой прием на текущий момент 
![image](https://github.com/kinguru-io/kinguru-next/assets/18754878/ea8456c8-f436-4e29-a926-224fe399cdcc)

2024-02-13 11:39 UTC, edelwud commented on src/components/uikit/Dropdown/Dropdown.recipe.ts
> +      lg: { w: "259px" },
чуть не пропустил, тут по идее должен быть `minW` вместо `w`

2024-02-13 11:51 UTC, edelwud requested changes

2024-02-13 11:51 UTC, edelwud commented on src/components/uikit/Dropdown/Dropdown.tsx
> +}
с абсолютным объектом в инициаторе будет сложно стилизировать кнопку, т.к. он будет получать все события, а не сам компонент кнопки, из решений: 
в DropdownInitiator завязаться рефом на корневой элемент и поставить на него листенер на клики, менять состояние в зависимости от того, был ли клик по компоненту
в этом случае понадобится контекст и компоненту нужно будет маркировать клиентской

2024-02-13 12:16 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.tsx
> +}
да, проверил, как линк кнопку не расстянешь рядом. есть еще вариант просто внутрь кнопки пихать. тогда для Аватара будет хорошо, потому что аватар через <span> сделан

2024-02-13 16:13 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.tsx
> +  setOpen: (_value: boolean) => {},
open - глагол

opened или что-нибудь подобное

2024-02-13 16:13 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.tsx
> +  return <div onClick={clickHandler}>{children}</div>;
`role="button"`

2024-02-13 16:20 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.tsx
> +  return <div onClick={clickHandler}>{children}</div>;
`<div role="button" tabindex="0">Нажми меня</div>`
https://doka.guide/a11y/role-button/

2024-02-14 07:27 UTC, kiruushaaa requested changes

2024-02-14 07:27 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.tsx
> +    <div role="button" onClick={clickHandler}>
`tanIndex="0"` не забудь

2024-02-14 07:27 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.recipe.ts
> +      lg: { menu: { w: "259px" } },
как Максим говорил поменять на `maxWidth`, но в base добавить `minWidth`

2024-02-14 07:27 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.stories.tsx
> +const meta = {
если в стори не видно тогла hidden true/false, добавь `args: { hidden: 'boolean' }`

2024-02-14 07:27 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.tsx
> +      className={classes.menu + " " + customDivider({})}
[чуть иначе](https://panda-css.com/docs/concepts/merging-styles#merging-config-recipe-and-style-object)

2024-02-14 07:27 UTC, kiruushaaa commented on panda.config.ts
> +      customDivider: {
@edelwud оно будет нормально смотреться в `theme/patterns.ts`?

2024-02-14 07:27 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.tsx
> +  const classes = dropdown({ size });
возможно лучше переименовать во что-нибудь типа `dropdownSlot` и передать его в контекст

2024-02-14 07:27 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.tsx
> +export function Dropdown({ children, size }: DropdownProps) {
по умолчанию `size = 'sm'`? @edelwud

2024-02-14 07:44 UTC, edelwud commented on panda.config.ts
> +      customDivider: {
Да, думаю там самое место

2024-02-14 12:17 UTC, edelwud commented on src/components/uikit/Dropdown/Dropdown.tsx
> +export function Dropdown({ children, size }: DropdownProps) {
да, дефолт = sm

2024-02-14 12:27 UTC, edelwud commented on src/components/uikit/Dropdown/Dropdown.recipe.ts
> +      bg: "token(color.neutral.5)",
тут забыл `s`
```suggestion
      bg: "token(colors.sneutral.5)",
```

2024-02-14 14:04 UTC, kiruushaaa commented on src/components/uikit/Dropdown/Dropdown.recipe.ts
> +      bg: "token(color.neutral.5)",
не, у нас нет sneutral)

2024-02-14 15:35 UTC, edelwud commented on src/components/uikit/Dropdown/Dropdown.recipe.ts
> +      bg: "token(color.neutral.5)",
)

2024-02-14 15:35 UTC, edelwud approved these changes
выглядит хорошо

2024-02-14 16:15 UTC, kiruushaaa approved these changes

2024-02-14 16:22 UTC, merged