feat(KINGU-79): create header and footer
kinguru-io/kinguru-next pull request #445
Opened 2024-02-15 19:06 UTC by okyxxxf

Почти все готово, необходимо только:
- Добавить ссылки необходимые;
- Подправить отступы в хедере; 
- Реализовать мобильные версии.

2024-02-15 22:13 UTC, edelwud requested changes
Общие рекомендации:
1. нужны стори для хидера и футера
2. папку footer/header переименовать в Footer/Header, файлики компонентов называть с большой буквы
3. Свитчер вцелом не нравится, посомтри референсы, как его можно организовать
4. Не нравится то, что используешь много `css` функций, надо это утаскивать в рецепт (или слот рецепт)
Пока что так, добавь стори - будет более понятно по стилям

2024-02-15 22:13 UTC, edelwud commented on src/components/footer/footer.tsx
> +          px: "486px 435px",
ой, а это что такое)

2024-02-15 22:13 UTC, edelwud commented on src/components/footer/footer.tsx
> +          maxWidth: "1920px",
а зачем это ограничение?

2024-02-15 22:13 UTC, edelwud commented on src/components/footer/languageDropdown.tsx
> +    router.push(newPathname!);
не нравится, нет проверок, оператор `!` - плохо, `console.log` - плохо

2024-02-15 22:13 UTC, edelwud commented on src/components/footer/footer.tsx
> +    { name: t("navbar.price"), href: "/price" },
и этот массив надо унести в свитчер

2024-02-16 08:11 UTC, okyxxxf commented on public/locales/en/common.json
> +    "all_rights_reserved": "2023  Kinguru. All rights reserved"
как в дизайне)

2024-02-16 12:12 UTC, edelwud commented on src/components/Footer/Footer.tsx
> +import linkedinIcon from "~/public/img/footerIcons/LinkedIn.svg";
если в спрайты - нужно растеризировать, в векторе кажется будет лучше

2024-02-16 15:37 UTC, kiruushaaa commented on src/components/Header/HeaderLinks.tsx
> +}
так делают обычно, на сео вряд ли это влияет 🤔

2024-02-16 15:44 UTC, kiruushaaa commented on src/components/Header/HeaderLinks.tsx
> +}
@okyxxxf + добавить зону для клика (padding: 5px например)

2024-02-19 08:17 UTC, kiruushaaa requested changes

2024-02-19 08:17 UTC, kiruushaaa commented on src/components/Footer/Footer.recipe.tsx
> +    },
используй `<Container />` из панды

2024-02-19 08:17 UTC, kiruushaaa commented on src/components/Footer/Footer.tsx
> +              </Link>
Однотипная вещь
- вынести в массив объектов
- мапить в разметке
- убрать role у картинок
- alt текст бессмысленный. `Follow us on {socialMedia}` @edelwud кажется корректнее? Если да, то перевод добавить какой

2024-02-20 07:28 UTC, kiruushaaa commented on src/components/Header/UserSection.tsx
> +  t: any;
почему так, а не useTranslations?

2024-02-20 07:49 UTC, okyxxxf commented on src/components/Header/UserSection.tsx
> +  t: any;
в асинхронном компоненте, нельзя вызывать useTranslations

2024-02-20 07:49 UTC, kiruushaaa requested changes

2024-02-20 07:49 UTC, kiruushaaa commented on src/components/Header/Header.tsx
> +      <Container className={classes.headerWrapper} px="370px" maxW={"1920px"}>
px не нужен. он есть внутри и нужен только для безопасного расстояния (пикселей 20 например с двух сторон)

2024-02-20 07:49 UTC, kiruushaaa commented on src/components/Footer/Footer.tsx
> +                    alt={`Follow us on ${name}`}
тут перевод нужен

2024-02-20 07:49 UTC, kiruushaaa commented on src/components/Footer/Footer.tsx
> +      <Container className={classes.footerWrapper} px="430px" maxW={"1920px"}>
то же самое с padding как и в хедере

2024-02-20 07:49 UTC, kiruushaaa commented on public/locales/pl/common.json
> +    "lang_ru": "Russian",
переводы больше не нужны тут, если названия остаются на оригинальном языке

2024-02-20 07:49 UTC, kiruushaaa commented on src/components/Footer/Footer.tsx
> +      <Container className={classes.footerWrapper} px="430px" maxW={"1920px"}>
https://play.panda-css.com/cGoR3rVkpH

2024-02-20 08:06 UTC, kiruushaaa commented on src/components/Header/UserSection.tsx
> +  t: any;
@edelwud help 🫠

2024-02-20 08:45 UTC, edelwud commented on src/components/Header/UserSection.tsx
> +  t: any;
https://next-intl-docs.vercel.app/docs/environments/server-client-components#async-components

2024-02-20 15:12 UTC, edelwud commented on src/components/Header/HeaderLinks.tsx
> +type navigationLink = {
Назови тип с большой буквы)

2024-02-20 18:57 UTC, kiruushaaa requested changes

2024-02-20 18:57 UTC, kiruushaaa commented on src/components/Footer/LanguageDropdown.tsx
> +  const lang = new Intl.DisplayNames(locales, { type: "language" });
@edelwud вроде же решили использовать статичный объект, потому что мало языков?

в любом случае создавать экземпляр интла нужно точно вне компонента

2024-02-20 18:58 UTC, kiruushaaa commented
еще есть предложение закрыть пр и открыть заново

(очень много не resolved комментариев)

2024-02-20 22:02 UTC, edelwud commented on src/components/Footer/LanguageDropdown.tsx
> +  const lang = new Intl.DisplayNames(locales, { type: "language" });
Intl.DisplayNames выглядит перспективно, вцелом Intl можно будет применить в будущем и для формирования цен
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

2024-02-20 22:03 UTC, edelwud commented
@okyxxxf переоткрой этот PR, пройдемся ещё раз по изменениям

2024-02-20 22:17 UTC, closed without merging