feat(KINGU-89): profile image picker
kinguru-io/kinguru-next pull request #459
Opened 2024-02-20 16:36 UTC by kiruushaaa

Fixes #

2024-02-20 16:41 UTC, kiruushaaa commented on src/lib/actions/file-upload/actions.ts
> +import { v4 as uuid } from "uuid";
если будет использоваться, то нужно будет добавить в зависимости проекта

2024-02-20 16:44 UTC, edelwud commented on src/lib/actions/file-upload/actions.ts
> +import { v4 as uuid } from "uuid";
я бы этого парня посмотрел)
https://nodejs.org/api/crypto.html#cryptorandomuuidoptions

2024-02-20 17:13 UTC, edelwud requested changes

2024-02-20 17:13 UTC, edelwud commented on src/components/common/form/input-profile-image/ProfileImagePicker.tsx
> +  // TODO add validation
https://gist.github.com/AndersonNascimentoDosSantos/b3b8f760f3a431fe9e0ee440f5b0e2d4
разруливают refine'ами на стороне фронтэнда
с беком пока не понятно как поступить

2024-02-20 17:13 UTC, edelwud commented on src/lib/actions/file-upload/actions.ts
> +} as S3ClientConfig);
хочется это куда-то вынести, возможно куда-то в корень

2024-02-20 17:13 UTC, edelwud commented on src/lib/actions/file-upload/actions.ts
> +} as S3ClientConfig);
еще беспокоют энвы, можно попробовать вот эту штуковину
https://env.t3.gg/docs/nextjs

2024-02-20 17:13 UTC, edelwud commented on src/lib/actions/file-upload/actions.ts
> +export async function uploadProfileImage(data: FormData, key: string) {
хочется завязаться на `AuthFormState`, переименовав его в `FormState`
будет один интерфейс, с которым можно будет удобно работать в формах

2024-02-20 17:13 UTC, edelwud commented on src/components/common/form/input-profile-image/ProfileImagePicker.tsx
> +      Загрузите фото
текстовочки в переводы нада)

2024-02-20 17:13 UTC, edelwud commented on src/lib/actions/file-upload/actions.ts
> +    await fetch(presignedURL, { method: "PUT", body: image });
тут какой момент, фетч должен случиться на фронте, а фронту передать `presignedUrl`

2024-02-20 17:13 UTC, edelwud commented on src/lib/actions/file-upload/actions.ts
> +}
она по идее не будет нужна, как только фронт начнет получать `presignedUrl`

2024-02-20 17:13 UTC, edelwud commented on src/lib/actions/file-upload/actions.ts
> +    return JSON.stringify(e);
попробовать разрулить с помощью `FormState`

2024-02-20 18:05 UTC, kiruushaaa commented on src/components/common/form/input-file/InputFile.tsx
> +//TODO maybe worth adding styles when navigate from keyboard?
да

2024-02-20 18:06 UTC, kiruushaaa commented on src/components/common/form/input-file/InputFile.tsx
> +  onChange,
точно)

2024-02-20 18:22 UTC, kiruushaaa commented on src/lib/actions/file-upload/actions.ts
> +export async function uploadProfileImage(data: FormData, key: string) {
тут FormData, потому что некст не все пропускает параметрами для сервер экшена

но эту штуку так же можно сделать фабрику createFormAction

2024-02-21 09:41 UTC, kiruushaaa commented on src/components/common/form/input-profile-image/ProfileImagePicker.tsx
> +  imgPlaceholderSrc?: string;
переименую в imageSrc, который можно будет использовать для уже имеющихся фотографий или вдруг плейсхолдера

2024-02-21 20:44 UTC, merged