feat(KINGU-92): create slider component
kinguru-io/kinguru-next pull request #476
Opened 2024-02-26 20:53 UTC by okyxxxf

Создал компонент карусель остались вопросы:
1. И вопрос на счет размера, он должен быть статический или динамический, и каким образом это можно реализовать?
2. Бесконечная ли прокрутка?

2024-02-26 21:04 UTC, kiruushaaa commented
Статичный слайдер конечно бесполезная вещь, если ты делаешь компонент)

@edelwud как насчет моего предложения взять слайдер на scroll snap? Библиотеку поищу что скидывал, вроде закроет все нужды

брать готового монстра с кучей логики как-то стремно, а свой писать очень долго

2024-02-26 21:33 UTC, kiruushaaa commented
here you are [no](https://github.com/richardscarrott/react-snap-carousel)

2024-02-26 21:34 UTC, kiruushaaa commented
С виду поддержка серверных компонентов есть. То есть паттерн когда серверный (картинки) вставляется чилдренов в клиентский

🍯

2024-02-27 03:36 UTC, edelwud commented
ой, мне нравится, выглядит хорошо и кастомизируется просто

По rsc: компонента так или иначе была бы клиентской, с этим проблем не должно быть

2024-02-27 10:24 UTC, edelwud requested changes
на дейлике разобрали:
1. слайдер динамического размера
2. с бесконечной прокруткой
3. надо бы заюзать бибиотеку для слайдера

2024-02-27 10:25 UTC, kiruushaaa commented
> на дейлике разобрали:
> 
> 1. слайдер динамического размера
> 2. с бесконечной прокруткой
> 3. надо бы заюзать бибиотеку для слайдера

Библиотека может быть другая
Я искал не слишком старые (в этой 1 месяц назад коммит был) и на скролл снапе

2024-02-27 13:14 UTC, kiruushaaa commented on src/components/uikit/Slider/Slider.recipe.ts
> +      h: "220px",
что-то не то

2024-02-27 13:16 UTC, kiruushaaa commented on src/components/uikit/Slider/Slider.tsx
>        >
почему див а не кнопка?

2024-02-27 13:16 UTC, kiruushaaa commented on src/components/uikit/Slider/Slider.tsx
>        >
аналогично. почему не кнопка?

2024-02-27 13:16 UTC, kiruushaaa commented on src/components/uikit/Slider/Slider.tsx
> +  console.log(activePageIndex);
не забудь убрать

2024-02-27 13:20 UTC, kiruushaaa commented on src/components/uikit/Slider/Slider.tsx
> +    <li className={cx(classes.item, isSnapPoint ? classes.itemSnapPoint : "")}>
в панде лучше добавлять `data-snap-point={isSnapPoint}` и добавлять нужные стили

2024-02-27 13:23 UTC, kiruushaaa requested changes

2024-02-27 13:23 UTC, kiruushaaa commented on package.json
- добавить пакеты в `.projentc.ts`
- локально запустить `npx projen`

2024-02-27 15:12 UTC, edelwud commented on panda.config.ts
> +import { SliderSlot } from "./src/components/uikit/Slider/Slider.recipe";
в качестве консистентности давай тоже с маленькой

2024-02-27 15:14 UTC, edelwud commented
Пакеты, которые устанавливаешь через npm, должны содержаться в `.projenrc.ts`
Вернее даже как написал Кирилл, сначала добавляешь пакет в `.projenrc.ts` (в секцию deps или devDeps), а потом прокатываешь `npx projen`

2024-02-27 15:44 UTC, edelwud commented on src/components/uikit/Slider/Slider.recipe.ts
> +      top: "calc(100% / 2 - 18.5px)",
```suggestion
      top: "50%",
      transform: "translateY(-50%)",
```

2024-02-27 18:02 UTC, kiruushaaa requested changes

2024-02-27 18:25 UTC, kiruushaaa approved these changes

2024-02-27 18:31 UTC, merged