feat: [initial] venue public page
kinguru-io/kinguru-next pull request #482
Opened 2024-02-28 15:31 UTC by kiruushaaa

Fixes #

2024-02-28 15:31 UTC, kiruushaaa commented on src/pages/[locale]/places/index.tsx
плейсхолдер чтобы можно было переходить на страницу

2024-02-28 20:48 UTC, edelwud commented on src/app/[locale]/venue/[id]/page.tsx
> +        <AspectRatio ratio={16 / 9}></AspectRatio>
Насчёт карты: пару моментов можно обсудить на дейли, видится сейчас mapbox (мы его уже используем, достаточно хорошо кастомизируется, webgl все дела, правда большой он сам по себе)

2024-02-28 20:48 UTC, edelwud commented on src/pages/[locale]/places/index.tsx
Немного странно, что это в pages роутере, может вынести на app?

2024-03-04 08:37 UTC, edelwud commented on src/app/[locale]/venue/[slug]/VenueDescriptionCollapse.tsx
из моментов, лучше директориб назвать src/app/[locale]/venues (слагом выбирать конкретный, на странице показывать список)

2024-03-05 11:59 UTC, edelwud requested changes

2024-03-05 11:59 UTC, edelwud commented on prisma/schema.prisma
> +  image            String?
будет обязательным для площадки

2024-03-05 11:59 UTC, edelwud commented on prisma/schema.prisma
> +  locationMapboxId String?
по идее, это тоже

2024-03-05 11:59 UTC, edelwud commented on prisma/schema.prisma
> +  width          Int          @default(100)
давай такие же сделаем как и в PremiseResources:
```suggestion
  height         Int          @default(720)
  width          Int          @default(405)
```

2024-03-05 11:59 UTC, edelwud commented on src/app/[locale]/venues/[slug]/page.tsx
> +            mapboxId={venue.locationMapboxId || ""}
после прокатки миграции можно будет такое)
```suggestion
            mapboxId={venue.locationMapboxId}
```

2024-03-05 11:59 UTC, edelwud commented on src/app/[locale]/venues/[slug]/page.tsx
> +          <Image src={image || ""} alt={t("image_alt", { name: name })} fill />
и тут тоже
```suggestion
          <Image src={image} alt={t("image_alt", { name: name })} fill />
```

2024-03-05 11:59 UTC, edelwud commented on src/components/premise/PremiseListing.tsx
давай директорию зала тоже с большой буквы типа Premise

2024-03-05 11:59 UTC, edelwud commented on src/components/premise/PremiseView.tsx
> +                <sup>2</sup>)
можно копнуть в эту сторону:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#unit_2
у `next-intl` есть такая обертка, выглядит перспективно:
https://next-intl-docs.vercel.app/docs/usage/numbers

Из нюансов, кажись там нет `unit: "area-square-meter"`

2024-03-05 11:59 UTC, edelwud commented on src/components/premise/PremiseView.tsx
> +          {t("from")} {priceForHour}
давай такую же штуку, только с ценами:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#currency_2

2024-03-05 11:59 UTC, edelwud commented on src/components/premise/PremiseView.tsx
> +        </PremisePrice>
Не хочешь внести в этот компонент агрегацию минимальной цены, передав пропcом массив из дней?

2024-03-05 11:59 UTC, edelwud commented on src/components/venue/VenueMap.tsx
давай карту сделаем отдельным компонентом, будет точно нужна еще и на странице события

2024-03-05 11:59 UTC, edelwud commented on src/layout/block/VenueMainInfoLayout.tsx
> +        opacity: bgImageSrc ? "0.9" : "1",
а в каком случае будет `"1"` ?)

2024-03-05 11:59 UTC, edelwud commented on src/layout/block/VenueMainInfoLayout.tsx
> +        backgroundColor: bgImageSrc ? "neutral.5" : "neutral.4",
такая я же штука, по идее можно сделать `bgImageSrc` необязательным

2024-03-06 00:07 UTC, edelwud approved these changes

2024-03-06 08:57 UTC, merged