feat(KINGU-100): create event page
kinguru-io/kinguru-next pull request #498
Opened 2024-03-06 22:28 UTC by okyxxxf

что еще не готово:
- Вариант для слайдер;
- Перевод;
- Поправить получение адреса;
- Добавить сущность для понравившихся событий:

2024-03-07 08:34 UTC, kiruushaaa commented on src/components/uikit/Avatar/Avatar.tsx
> +export function AvatarWrapper({ size = "sm", children }: AvatarWrapperProps) {
вот это делать не нужно

2024-03-07 08:35 UTC, kiruushaaa commented on src/components/uikit/Button/Button.tsx
> +  size = "sm",
и вот это тоже

потому что рецепты могут использоваться без компонента (ссылку например стилизовать)
поэтому там лежит defaultVariants везде

2024-03-07 10:55 UTC, edelwud requested changes
пурпоз все тот же, меньше инлайн стайлинга, больше уноси компоненты
старайся раньше выкатывать pr чтобы его можно было смотреть заранее и подсказывать, потому что тут миллин проблем и упустить что-то очень просто

2024-03-07 10:55 UTC, edelwud commented on src/app/[locale]/event/[slug]/page.tsx
> +        <Flex direction="column" gap="20px" maxW="1180px">
это в лэйаут

2024-03-07 10:55 UTC, edelwud commented on src/app/[locale]/event/[slug]/page.tsx
> +            name={topic || ""}
почему у тебя может отсутстовать топик, он ж обязательный
что будет, если постер будет отсутствовать?

2024-03-07 10:55 UTC, edelwud commented on src/app/[locale]/event/[slug]/page.tsx
> +                </Card>
отдельный компонент EventCardView

2024-03-07 10:55 UTC, edelwud commented on src/app/[locale]/event/[slug]/page.tsx
переименуй в папку в events

2024-03-07 10:55 UTC, edelwud commented on src/components/event/EventMainInfo.tsx
> +      text: starts.toLocaleDateString("ru-RU", {
а чего прибил локаль?
у интла есть что-то для форматирования дат

2024-03-07 10:55 UTC, edelwud commented on src/components/event/EventMainInfo.tsx
> +      const { address } = data.features[0].properties;
```suggestion
      const { address } = data.features.at(0)?.properties;
```

2024-03-07 10:55 UTC, edelwud commented on src/components/uikit/Tag/Tag.tsx
> +  size = "sm",
в рецепт давай это

2024-03-07 10:55 UTC, edelwud commented on src/components/uikit/Tag/Tag.tsx
> +  css: cssProp,
а вот это ради чего?

2024-03-07 10:55 UTC, edelwud commented on src/components/event/EventDescription.tsx
> +        />
глянь как у @kiruushaaa сделан коллапс

2024-03-07 11:30 UTC, kiruushaaa commented on src/app/[locale]/event/[slug]/page.tsx
> +        <Flex direction="column" gap="20px" maxW="1180px">
этого вообще не должно быть

`<Container>` все покрывает

2024-03-07 11:32 UTC, kiruushaaa commented on src/components/uikit/Tag/Tag.tsx
> +  css: cssProp,
это еще я добавлял. по сути не нужно с `<Float>`

2024-03-07 13:20 UTC, okyxxxf commented on src/components/uikit/Tag/Tag.tsx
> +  size = "sm",
в рецепт, как значение по умолчанию занисти?

2024-03-07 13:20 UTC, okyxxxf commented on src/components/event/EventMainInfo.tsx
> +      text: starts.toLocaleDateString("ru-RU", {
пока не добавлял перевод совсем, в скором времени добавлю

2024-03-07 13:21 UTC, okyxxxf commented on src/app/[locale]/event/[slug]/page.tsx
> +                />
На счет аватара, сделать как когда то обсуждали, сокращение имени?

2024-03-07 13:22 UTC, okyxxxf commented on src/app/[locale]/event/[slug]/page.tsx
> +/* eslint-disable @typescript-eslint/no-shadow */
на строке 145, там такие же названия переменных, по сути убереться когда вынесу популяные события в отдельный компонент

2024-03-07 13:23 UTC, okyxxxf commented on next.config.js
> +      }
Выдавало ошибку, скорее всего faker оттуда брал какие то изображения

2024-03-07 14:00 UTC, edelwud commented on src/app/[locale]/event/[slug]/page.tsx
> +  });
(по убыванию, сорри за путаницу)

2024-03-07 14:01 UTC, edelwud commented on src/app/[locale]/event/[slug]/page.tsx
> +                />
есть кейс, при котором у пользователя может не быть имени
давай картину профиля вставим

2024-03-08 08:07 UTC, kiruushaaa requested changes

2024-03-08 08:07 UTC, kiruushaaa commented on public/img/defaultImages/event.png
это конечно окей. но
- сжать картинку (если сжал, то ок)
- наделать под разные разрешения экранов (@edelwud некст не делает так сразу?)

но, если посмотреть дальше
- зачем вообще отдельная картинка, если это текст на фоне?
- взять свг (будет весить куда меньше чем самый сжатый пнг)
- сделать компонент, который расстягивается с свг по центру. или как мне кажется будет лучше сделать паттерн чисто на цсс. вставив картинку при помощи `backgroundImage: '<svg/>'`


cc @edelwud

2024-03-08 08:07 UTC, kiruushaaa commented on src/app/[locale]/events/[slug]/page.tsx
> +                avatars={usersOnEvent.map(({ user: { image, name } }: any) => ({
откуда any? 🤔

2024-03-08 08:07 UTC, kiruushaaa commented on src/app/[locale]/events/[slug]/page.tsx
> +          {tags.map((tag: any) => (
откуда any? 🤔

2024-03-09 10:42 UTC, kiruushaaa requested changes

2024-03-09 10:42 UTC, kiruushaaa commented on src/components/event/EventDescription.tsx
> +function ExpandStateIcon({ isShown }: { isShown: boolean }) {
вот эту штуку точно в отдельный компонент вынести и импортировать в premise/event

2024-03-09 10:42 UTC, kiruushaaa commented on src/components/event/EventDescription.tsx
> +function ExpandStateIcon({ isShown }: { isShown: boolean }) {
ArrowIcon например. Описать проп direction. `type ArrowDirection = 'up' | down' | 'right' | 'left`

Например потом в слайдере можно поправить

2024-03-09 10:42 UTC, kiruushaaa commented on src/components/event/EventSpeakersSlider.tsx
> +                        zIndex={1}
```suggestion
                        zIndex="1"
```
для красоты)

2024-03-09 10:42 UTC, kiruushaaa commented on src/components/uikit/Button/Button.tsx
> -  iconPosition = "left",
это не стили, а data-attribute. В целом ничего не поменяется, но все же

2024-03-10 08:14 UTC, kiruushaaa requested changes

2024-03-10 08:14 UTC, kiruushaaa commented on src/pages/[locale]/old events/[id].tsx
ох, откуда пробелы)) => `old-events`
забудь про пробелы в фс!

2024-03-11 01:54 UTC, edelwud requested changes

2024-03-11 01:54 UTC, edelwud commented on src/components/event/EventCardView.tsx
> +                  image: image || "",
?

2024-03-11 01:54 UTC, edelwud commented on src/components/event/EventCardView.tsx
> +          src={poster || ""}
?

2024-03-11 01:54 UTC, edelwud commented on src/components/event/EventSpeakersSlider.tsx
> +            );
а что тут за вычисления?)

2024-03-11 01:54 UTC, edelwud commented on src/app/[locale]/events/[slug]/page.tsx
> +                  image: image || textLogo.src,
?

2024-03-11 01:54 UTC, edelwud commented on src/components/event/EventLikeButton.tsx
> +  };
сюда нужен оптимистик

2024-03-11 01:54 UTC, edelwud commented on src/components/event/EventLikeButton.tsx
> +export function EventLikeButton({ id }: EventImageProps) {
экшен нужно провайдить пропом от серверного компонента

2024-03-11 01:54 UTC, edelwud commented on src/lib/actions/likedEvent/getLikedEvents.ts
> +      userId: session.user?.id,
```suggestion
  if (!session || !session.user) return [];
  return prisma.userLikedEvents.findMany({
    where: {
      userId: session.user.id,
```

2024-03-11 01:54 UTC, edelwud commented on src/lib/actions/likedEvent/toggleLike.ts
> +  if (userId) {
сокращай вложенность

2024-03-11 01:54 UTC, edelwud commented on src/lib/actions/likedEvent/toggleLike.ts
> +export async function toggleLikeEvent(eventId: string) {
не, тогл нам не нужен на бэке, либо лайк (если уже есть - игнорим), либо 403 если не авторизован
отдельная функция для удаления лайка нужна

2024-03-11 06:38 UTC, okyxxxf commented on src/components/event/EventSpeakersSlider.tsx
> +            );
рейтинг спикера исходя из его комментариев и оценок на них

2024-03-13 10:49 UTC, kiruushaaa requested changes

2024-03-13 10:49 UTC, kiruushaaa commented on src/components/event/EventLikeButton.tsx
> +      <Button
чилдреном добавить переводы для кнопки

Нравится/Не нравится
Добавить в избранное/Удалить из избранного

2024-03-13 10:49 UTC, kiruushaaa commented on src/components/uikit/ArrowIcon/ArrowIcon.tsx
> +  return <div className={arrowIcon({ direction })}></div>;
=> `<span>`
и если будет ломаться верстка `display: 'inline-block'`

2024-03-13 10:49 UTC, kiruushaaa commented on src/components/uikit/Button/Button.tsx
> -  iconPosition = "left",
верни обратно

2024-03-13 10:49 UTC, kiruushaaa commented on src/components/uikit/Button/Button.tsx
> +      )}
- добавить data-attr какой-нибудь для этого блока. например label, потому что это лейбл кнопки
- внутри варианта `iconOnly` по этому атрибуту добавлять `srOnly: true`

2024-03-13 10:49 UTC, kiruushaaa commented on public/img/defaultImages/event.png
оно где-то используется еще?

2024-03-13 10:49 UTC, kiruushaaa commented on src/lib/actions/event/likes/deleteLike.ts
> +}
добавляй пустые строки между логическими кусками кода

2024-03-13 10:49 UTC, kiruushaaa commented on src/components/uikit/DefaultImage/DefaultImage.tsx
> +      display="inline"
тогда уж лучше сразу `<span>` через `css()` делать

2024-03-13 10:49 UTC, kiruushaaa commented on src/components/uikit/ArrowIcon/ArrowIcon.recipe.ts
> +    height: "8px",
через em будет нормально выглядеть?

2024-03-13 10:49 UTC, kiruushaaa commented on src/components/event/EventSpeakersSlider.tsx
> +              comments.length === 0 ? 0 : ratingSum / comments.length;
в одну функцию можно написать. у коллбека есть параметр `array`

да и кажется `_avg` призмы справится сразу

2024-03-13 10:49 UTC, kiruushaaa commented on src/components/uikit/DefaultImage/DefaultImage.stories.tsx
> +  ),
```
component: DefaultImage,
decorators: [(Story) => <Box><Story></Box>]
```

2024-03-13 10:49 UTC, kiruushaaa commented on src/components/event/EventLikeButton.tsx
> +          )
попробуй одну иконку использовать, но менять в ней стили

2024-03-13 10:49 UTC, kiruushaaa commented on src/components/event/EventDescription.tsx
> +export function EventDescription({ description }: EventDescriptionProps) {
идентичный же компонент как и для Venue. Вынеси в отдельный компонент и просто меняй пропами что нужно: переводы и текст

2024-03-13 10:49 UTC, kiruushaaa commented on src/components/event/EventCardView.tsx
> +              />
что это?)

2024-03-13 10:49 UTC, kiruushaaa commented on public/locales/pl/common.json
> +    }
что-то пахнет гуглом. прогони через аи или https://context.reverso.net/перевод/английский-русский/

2024-03-13 12:29 UTC, okyxxxf commented on src/components/event/EventCardView.tsx
> +              />
это ссылка на событие, проверка чтобы ошибки не было

2024-03-13 16:22 UTC, edelwud commented on src/components/event/EventSpeakersSlider.tsx
> +              comments.length === 0 ? 0 : ratingSum / comments.length;
```ts
const speakersWithRatingResult = await Promise.allSettled(
  event.speakersOnEvent.map(({ speakerId, ...props }) =>
    prisma.speakerComment
      .aggregate({
        where: { speakerId },
        _avg: { rating: true },
      })
      .then(({ _avg: { rating } }) => ({ rating, ...props })),
  ),
);
```

2024-03-13 16:24 UTC, kiruushaaa requested changes

2024-03-13 16:24 UTC, kiruushaaa commented on src/components/common/description/Description.tsx
> +import { ArrowIcon } from "../../uikit/ArrowIcon/ArrowIcon";
```suggestion
import { Button, TextCollapse, ArrowIcon } from "@/components/uikit";
```

2024-03-13 16:24 UTC, kiruushaaa commented on src/app/[locale]/venues/[slug]/page.tsx
> +          showMoreTranslate={t("show_more")}
```suggestion
          showLessLabel={t("show_less")}
          showMoreLabel={t("show_more")}
```
чтобы не глагол

2024-03-13 16:24 UTC, kiruushaaa commented on src/components/event/EventSpeakersSlider.tsx
>                return acc + item.rating;
что-то непонятное опять)

`return acc + item.rating / array.length`

2024-03-13 16:24 UTC, kiruushaaa commented on src/components/uikit/Button/Button.tsx
> +  label = true,
проп не нужен

2024-03-13 16:24 UTC, kiruushaaa commented on src/components/uikit/Button/Button.tsx
> +        data-label={label}
просто `data-label`
аналогично если карточка интерактивная, то там просто добавляется `data-interactive`

2024-03-13 16:26 UTC, kiruushaaa commented on src/components/event/EventCardView.tsx
> +              />
Странная вещь. Обычная же ссылка. И почему инпут 🤔

и какая ошибка?

2024-03-13 16:32 UTC, edelwud commented on src/components/event/EventSpeakersSlider.tsx
>                return acc + item.rating;
лучше посчитай через призму, забьем до смерти ноду, если математику ей дадим
https://github.com/kinguru-io/kinguru-next/pull/498#discussion_r1523570107

2024-03-13 16:37 UTC, edelwud commented on src/lib/actions/event/likes/isLikedEvent.ts
> +  });
тут я чето с советом промахнулся
сделай findFirst, если найдется - true, нет - false

2024-03-13 16:39 UTC, edelwud commented on src/lib/actions/event/likes/deleteLike.ts
> +  if (!likedEvent) return;
по идее у тебя не будет ошибки, если будешь удалять строку которой нет
так что проверка не нужна

2024-03-13 16:52 UTC, okyxxxf commented on src/components/event/EventCardView.tsx
> +              />
инпут, сказал максим сделать. Ошибка по сути не влияет на работу, но в консоле высвечивается ReferenceError window is not defined

2024-03-13 20:54 UTC, edelwud requested changes

2024-03-13 20:54 UTC, edelwud commented on src/components/event/EventSpeakersSlider.tsx
> +      }[];
это уже не надо

2024-03-13 20:54 UTC, edelwud commented on src/app/[locale]/events/[slug]/page.tsx
> +              comments: { select: { rating: true } },
это тоже не надо

2024-03-13 20:54 UTC, edelwud commented on src/lib/actions/event/likes/deleteLike.ts
> +  });
а почему не `delete`?

2024-03-13 20:54 UTC, edelwud commented on src/lib/actions/event/likes/isLikedEvent.ts
> +  });
а тут `findUnique`

2024-03-14 22:44 UTC, kiruushaaa commented on panda.config.ts
> +          modal: { value: "110" },
Уже начинаем стрелять себе в ногу 🫠

оно не отображается корректно без этого?

если нет, то кажется пора менять на порталы. Что думаешь @edelwud ?
к

2024-03-14 23:03 UTC, okyxxxf commented on panda.config.ts
> +          modal: { value: "110" },
Корректно нет, теги и кнопки, которые позиционированны через float наезжают сверху

2024-03-15 07:52 UTC, kiruushaaa commented on panda.config.ts
> +          modal: { value: "110" },
@edelwud посоветовались с Сашей. В общем чтобы избежать выстрелов в ногу, нужно переписывать даже dropdown на порталы. 

В таком случае появляется задача написать портал, который создает fixed обертку, для которой нужно считать положение. К сожалению у меня не вышло только на цсс сделать такую же логику через `<dialog />`, поэтому даже для него нужно будет считать отступы, чтобы он прикреплялся к правой стороне элемента, поэтому для него тоже нужна отдельная задача.

Из вариантов добавить в беклог и вернуться во второй фазе с полной заменой паттерна создания всплывающих окон, потому что сейчас ни у кого особо нет времени. 

Но способ создания прям нужно поменять) Не зря же интернет стрелял себе в ногу с z-index столько лет 😁

2024-03-15 07:58 UTC, kiruushaaa commented on panda.config.ts
> +          modal: { value: "110" },
https://www.youtube.com/watch?v=w4CPbE_efWw

вот здесь абстрактное решение, которое в целом самое стабильное, но без `<dialog />`.
с `<dialog />` внутри такого портала поубавится проблем с добавление `onClickOutside` и удаления скролла. Скролл и сейчас можно убирать через `body:has(...)`, но стремно пока что использовать из-за непонятной поддержки браузерами

2024-03-15 10:08 UTC, edelwud commented on panda.config.ts
> +          modal: { value: "110" },
нужны порталы, но не сейчас, давай добьем этот компонент с z-index

2024-03-15 10:18 UTC, kiruushaaa commented on src/components/event/EventMainInfo.tsx
> +      const { address } = data.features[0].properties;
@edelwud оно выполняется на клиенте. тут, чтобы красиво, либо так, либо деструктуризация массива.

2024-03-17 04:12 UTC, edelwud requested changes

2024-03-20 18:07 UTC, edelwud approved these changes

2024-03-20 18:21 UTC, merged